[package]
name = "rust-figlet"
version = "0.1.0"
edition = "2021"
author = "dayatstuff"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
figlet-rs = "0.1"